DSM-PICK/PICK2023_SERVER_SPRING

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Application.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/mapper/ApplicationMapperImpl.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/ApplicationEntity.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/ClassroomMovementMapperImpl.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/entity/ClassroomMovementEntity.kt

🔀 :: (#21) 엔티티 수정

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryPicnicStudentElement.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryPicnicStudentList.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryApplicationSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/ApplicationPersistenceAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/StatusEntity.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt

🔀 :: (#34) 외출한 학생 리스트 조회 API

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/StatusEntity.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt

🔀 :: (#36) 외출신청 거절 API

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/UserQueryTeacherSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/dto/UserInfo.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserInfoResponse.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserResponse.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt

출석 확인 리스트 API를 짜기 위해서 그 날이 동아리인지 자습인지 api가 필요할 것 같다고 하셔서 그 코드는 미뤄두고 먼저 짜뒀던 feign 코드를 올리게 됐습니다.

🔀 :: (#43) 반 별 유저 목록 조회 feign 세팅

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryStudentStatusElement.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/response/QueryStudentStatusList.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/Classroom.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/CommandClassroomMovementSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/spi/QueryClassroomMovementSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/StatusCommandTeacherSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/dto/UserInfo.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/dto/response/UserResponse.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/entity/StatusEntity.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/mapper/ClassroomMapperImpl.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/ClassroomMovementRepository.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/adapter/ClassroomMovementPersistenceAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/persistence/entity/ClassroomEntity.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt

🔀 :: 출결 사항 리팩토링

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/api/AfterSchoolApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/api/dto/DomainCreateAfterSchoolStudentRequest.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/CommandAfterSchoolSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/AfterSchoolUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/AfterSchoolRepository.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/presentation/AfterSchoolWebAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/presentation/dto/requset/CreateAfterSchoolStudentRequest.kt

🔀 :: (#51) 방과후 학생 추가 API

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/TeacherApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/dto/request/DomainComebackStudentRequest.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/dto/request/ComebackStudentRequest.kt

🔀 :: (#52) 외출복귀 API

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/dto/request/DomainPicnicPassRequest.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/PicnicPassRequest.kt

🔀 :: (#57) 외출증 발급 API 

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/AfterSchool.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Application.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/Status.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/Classroom.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/ClassroomMovement.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/Club.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/SelfStudyDirector.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/Type.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/requst/DomainChangeSelfStudyDirectorRequest.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/CommandSelfStudyDirectorSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/QuerySelfStudyDirectorSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/SelfStudyDirectorSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/UserQuerySelfStudyDirectorSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/User.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/ChangeSelfStudyDirectorRequset.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt

aggregate setter 때문에 직접 접근 방식을 사용해서 전체를 불러와서 지정해주는데 data class로 깊은 복사 해서 하는게 좀더 효율적으로 보이는데 어케 생각함?

🔀 :: (#59) 자습감독선생님 변경

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/StatusType.kt

🔀 :: (#58) 상태에 자퇴 추가

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt

🔀 :: (#72) 반 별 학생 상태 변경 API에 자퇴도 추가

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/AdminApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt

기존에 typeId로 type을 가져와서 수정하던 로직을 date로 type을 가져와서 수정하도록 변경했습니다.

🔀 :: (#83) 타입 수정 api 변경

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/SelfStudyDirectorApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/request/DomainChangeSelfStudyDirectorRequest.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/api/dto/request/DomainRegisterSelfStudyDirectorRequest.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/CommandSelfStudyDirectorSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/ChangeSelfStudyDirectorRequest.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/dto/request/RegisterSelfStudyDirectorRequest.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt

🔀 :: (#75) 층별 자습감독 선생님 추가 API

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/error/AfterSchoolErrorCode.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/exception/AfterSchoolStudentExistsException.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/spi/QueryAfterSchoolSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/AfterSchoolUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/persistence/adapter/AfterSchoolPersistenceAdapter.kt

🔀 :: (#77) 방과후 중복학생 추가 시 예외처리

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/api/dto/response/QueryClubStudentList.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/club/usecase/ClubUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/spi/UserSpi.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt

studentIdList를 넘겨서 studentInfo를 가져오는 방식 때문에 User 쪽에서 4096 바이트 에러가 터지고 있었고 그걸 고치기 위해서 전체 쪽에서 가져온 뒤 필터링 하는 방식으로 변경했습니다.

🔀 :: (#84) 동아리 인원 조회 500 에러 수정

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/CommandSelfStudyDirectorSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/persistence/adapter/SelfStudyDirectorPersistenceAdapter.kt

🔀 :: (#81) 자습감독 선생님 일괄변경 버그 수정

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt

기존 나의 외출증을 가져오는 부분에서 하루가 지나도 그대로 떠있었고 이유가 status를 query할 때 날짜에 대한 필터링을 하지 않아서였고 오늘것만 가져오도록 수정했습니다

🔀 :: (#22) 외출증 조회 오늘것만 가져오도록 수정

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/error/ClassroomErrorCode.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/exception/CannotMovementWeekendException.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt

🔀 :: (#11) 주말 교실 이동 제한

---

pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt

@RequestParam으로 조회하던 걸 @RequestBody로 변경했습니다

🔀 :: (#16) UserFeign Http 4096 bytes 에러 해결

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/ClassroomType.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomUseCase.kt

TUE_CLUB, FRI_CLUB Eunm이 추가됨에 따라 미처 변경하지 못했던 조건문을 변경했습니다

🔀 :: (#17) Enum 추가에 따른 코드 변경

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/usecase/AdminUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/afterschool/usecase/AfterSchoolUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/UserQueryApplicationSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/classroom/usecase/ClassroomMovementUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/spi/UserQuerySelfStudyDirectorSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/selfstudydirector/usecase/SelfStudyDirectorUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/spi/UserQueryTeacherSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/dto/request/UserInfoRequest.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/common/feign/client/UserClient.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/user/persistence/UserPersistenceAdapter.kt

HTTP line is larger than 4096 bytes 에러를 해결을 하기 위해 Body로 요청으로 보내도록 코드를 수정했지만 명세서를 보지 못하고 클래스를 생성해서 코드를 작성하지 않을 걸 미처 확인하지 못하고 pr을 머지해서 오류가 생기게 되었습니다.

🔀 :: (#18) feign 요청 에러 코드 수정

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/spi/QueryStatusSpi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/persistence/adapter/StatusPersistenceAdapter.kt

오늘 날짜만 가져와야 하는 쿼리에서 where문이 날짜 대한 것이 없었기 때문에 수정했습니다

🔀 :: (#117) 쿼리 잘못된 부분 수정

---

pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/global/security/WebConfig.kt

🔀 :: (#154) 허용 도메인 추가

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/api/ApplicationApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/usecase/ApplicationUseCase.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/TeacherApi.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/api/dto/response/QueryMyBuckGradeAndClassNumResponse.kt
pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/admin/presentation/AdminWebAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/application/presentation/ApplicationWebAdapter.kt
pick-infrastructure/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/presentation/TeacherWebAdapter.kt

- 외출자 목록 확인, 주말급식 확인 등 학년 별로 필터링 할 때 담임 선생님일 시 담당 반으로 요청할 수 있도록 추가하였습니다.

🔀 :: (#171) 담당 반 조회 API

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt

- 담임 선생님이 아닐 시 기본 값으로 1로 반환하도록 변경하였습니다.

🔀 :: (#199) 담당 반 조회 API 수정

---

pick-application/src/main/kotlin/com/pickdsm/pickserverspring/domain/teacher/usecase/TeacherUseCase.kt

- 기본 값으로 1학년 1반으로 주는 코드를 수정하였습니다

🔀 :: (#203) 담당 반 조회 API 수정
